# Makefile for sample certificate directories

.PHONY:	all clean

all:	ECC/all DSA1024/all RSA-SHA2/all RSA-SHA1/all
clean:	ECC/clean DSA1024/clean RSA-SHA2/clean RSA-SHA1/clean

include ../tools/common.mk
